#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox --to-desktop II state=tiled
bspc rule -a URxvt:mutt desktop=III state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --randomize --bg-center ~/Pictures/feh/*
polybar top 
firefox
urxvt -e mutt
urxvt -e ncmpcpp
